### PR TITLE
Add confirmation for delete buttons

### PR DESCRIPTION
**Pull request by utkarshrpr**

### CODE REVIEW

**Comment by nishanthvijayan** [comment]
@utkarshrpr Try to see if you can improve the look of the popup.
I belieive the library has examples where it's done.
Also try to figure out if you can make the popout right

**Comment by utkarshrpr** [comment]
@nishanthvijayan I suggest that for the time-being let us go with this. We will get back on the UI at a later stage.

**Comment by nishanthvijayan** [comment]
@jainendra What do you think?

**Comment by jainendra** [comment]
@nishanthvijayan This has low priority, We'll do UI stuffs later

**Pull request merged**
