### PR TITLE
Support for date-time field

### PR DESCRIPTION
**Pull request by ankitdahiya95**
Issue #55

### CODE REVIEW

**Comment by nishanthvijayan** [comment]
Can you post a link to the plugin that you've used?

**Comment by ankitdahiya95** [comment]
[Bootstrap Datepicker](https://tarruda.github.io/bootstrap-datetimepicker/)

**Comment by nishanthvijayan** [comment]
They've used Bootstrap 2.2 in the documentation examples. Are you sure this is supposed to work with our version of bootstrap ?(v3)

**Comment by ankitdahiya95** [comment]
I am not sure. Should I try something else?

**Comment by utkarshrpr** [comment]
Plugin used:- [DateTime Picker](http://www.malot.fr/bootstrap-datetimepicker/index.php)

**Pull request merged**
